version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/bathrobe/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=podverta
      - POSTGRES_PASSWORD=Voa34Voa34
      - POSTGRES_DB=bathrobes

volumes:
  postgres_volume: